name: E2E Tests #name of my workflow

on:
  workflow_dispatch:
    inputs:
      testsPath:
        description: 'Path to Tests to be Executed'
        default: 'registration.tests.TestCase1'


  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC daily


  pull_request:
    branches:
      - main

jobs:
  E2E_edge_Windows_Test: #name of job
    runs-on: windows-latest
    permissions:
      checks: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Execute Tests
        continue-on-error: true
        run: mvn -DbrowserName="edge" -DheadlessExecution="false" -Dtest="${{github.event.inputs.testsPath}}" test
      - name: Generate Allure Report
        continue-on-error: true
        run: mvn allure:report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: Allure Report Windows edge
          path: target/site/allure-maven-plugin/index.html
      - name: Publish Report
        continue-on-error: true
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Report Edge_Windows
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit

  E2E_Chrome_Linux_Test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Run Tests in Headless Mode in chrome
        continue-on-error: true
        run: mvn -DBrowserName="Chrome" -DheadlessExecution="true" -Dtest="${{ github.event.inputs.testsPath}}" test
      - name: Generate Allure Report
        continue-on-error: true
        run: mvn allure:report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: Allure Report Ubuntu Test
          path: target/site/allure-maven-plugin/index.html
      - name: Publish Report
        continue-on-error: true
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Report Headless_Ubuntu
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit